project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "modules/**/*.qmd"
    - "!legacy/**"
    - "!modules/tests/**"
  resources:
    - "assets/**"

filters:
  - timeline
  - live
  - aptitek/download-fonts
  - aptitek/cards
  - aptitek/tabs
  - aptitek/ojs-bridge
  - aptitek/ojs-inputs
  - aptitek/bi-icons
  - aptitek/embed
  - aptitek/grid

website:
  title: "Aptispace"
  search: false
  sidebar:
    style: "docked"
    search: false
    contents: auto

format:
  html:
    theme:
      - theme/solarized/variables.scss
      - theme/solarized/base.scss
      - styles/components/index.scss
      - styles/simulators/index.scss
    toc: true
    code-copy: true
    echo: false
    ojs: true
    include-in-header:
      - text: '<script src="https://cdn.plot.ly/plotly-2.32.0.min.js"></script>'
      - text: |
          <script type="module">
            if (!window.aptitek) {
              const mod = await import("/assets/js/index.js");
              window.aptitek = Object.freeze({ ...mod });
            }
          </script>

